name: Run FetchUsers Daily at 11:55 AM Pakistan Time (Mon-Fri)

on:
  schedule:
    - cron: '19 7 * * 1-5'  # Runs at 12:15 PM Pakistan Time (07:15 UTC) on Monday to Friday

  workflow_dispatch:  # Allows manual triggering

jobs:
  run-fetch-users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run FetchUsers Script
        run: node fetchUsers.js
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
